import y07_08 from "../images/archives/2007-2008.jpg";
import y08_09 from "../images/archives/2008-2009.png";
import y09_10 from "../images/archives/2009-2010.png";
import y10_11 from "../images/archives/2010-2011.jpg";
import y11_12 from "../images/archives/2011-2012.png";
import y12_13 from "../images/archives/2012-2013.png";
import y13_14 from "../images/archives/2013-2014.jpg";
import y14_15 from "../images/archives/2014-2015.jpg";
import y15_16 from "../images/archives/2015-2016.jpg";
import y16_17 from "../images/archives/2016-2017.jpg";
import y17_18 from "../images/archives/2017-2018.jpg";
import y18_19 from "../images/archives/2018-2019.jpg";
import y19_20 from "../images/archives/2019-2020.jpg";
import y20_21 from "../images/archives/2020-2021.jpg";
import y21_22 from "../images/archives/2021-2022.jpg";
import y22_23 from "../images/archives/2022-2023.jpg";
import y23_24 from "../images/archives/2023-2024.png";
/* 
When adding new rosters, make sure to prepend to array in the format: 
[Year (str), Photo (filepath), Coaches (list of str), Captains (list of str), Players (list of str)]
*/
const rosters = [
  [
    "2023-2024",
    y23_24,
    ["Tanner Yuhas", "Sam Garncarz"],
    ["Tomer Poole-Dayan", "Davith Chan", "Iram Liu"],
    [
      "Simon Alford",
      "Parker Ashworth",
      "Amitai Cammy",
      "Roan Chadsey",
      "Nathaniel Chin",
      "Chris Fernandes",
      "Jacob Groner",
      "Zach Halevy",
      "Matthew Hui",
      "Dylan Kenniff",
      "Ren Kondo",
      "Ka Lok Ethan Lau",
      "Thomas Meyer",
      "Ben Nusbaum",
      "Calder Packard",
      "Spencer Peters",
      "Mason Raffo",
      "Milo Rappaport",
      "Micah Schuchman",
      "Elijah Sheridan",
      "Lewis Sisler",
      "Tyler Sprague",
      "Max Trager",
      "Neal Vasireddi",
      "Dylan Winchell",
      "Siming Wu",
      "Thomas Wu",
      "Ben Zou",
    ],
  ],
  [
    "2022-2023",
    y22_23,
    ["Tanner Yuhas", "James Mullmann (PC)"],
    ["Jack Waxman", "Sam Garncarz", "Tomer Poole-Dayan"],
    [
      "Simon Alford",
      "Gabe Biers-Browne",
      "Amitai Cammy",
      "Roan Chadsey",
      "Christopher Chan",
      "Davith Chan",
      "Alex Chen",
      "Nathaniel Chin",
      "Donovan Cho",
      "Christopher Fernandes",
      "Eric Freitag",
      "Ben Goldman",
      "Jacob Groner",
      "Matthew Hui",
      "Dylan Kenniff",
      "Sanjar Kushaliev",
      "Ka Lok Ethan Lau",
      "Daniel Lee",
      "Iram Liu",
      "Jake Ludgin",
      "Spencer Peters",
      "Mason Raffo",
      "Eli Robinson",
      "Elijah Sheridan",
      "Lewis Sisler",
      "Max Trager",
      "Mutty Un",
      "Dylan Winchell",
      "Thomas Wu",
      "Thomas Zhao",
    ],
  ],
  [
    "2021-2022",
    y21_22,
    ["Matt Burke", "Tanner Yuhas", "Justin Pierce"],
    ["Sam Hinson", "Ben Goldman", "Jack Waxman"],
    [
      "Gabe Biers-Browne",
      "Amitai Cammy",
      "Roan Chadsey",
      "Chris Chan",
      "Davith Chan",
      "Alex Chen",
      "Max Coleman",
      "Peter Deckerman",
      "Eric Freitag",
      "Sam Garncarz",
      "Ben Goldman",
      "Jacob Groner",
      "Elliot Hare",
      "Sam Hinson",
      "Matthew Hui",
      "Dylan Kenniff",
      "Sanjar Kushaliev",
      "Daniel Lee",
      "Iram Liu",
      "Patrick Moore",
      "James Mullman",
      "Ben Myers",
      "Spencer Peters",
      "Tomer Poole-Dayan",
      "Lewis Sisler",
      "Neal Vasireddi",
      "Jack Waxman",
      "Dylan Winchell",
      "Thomas Wu",
      "Thomas Zhao",
    ],
  ],
  [
    "2020-2021",
    y20_21,
    ["Matt Burke", "Wally Kwong", "Tanner Yuhas", "Justin Pierce"],
    [
      "David Maniloff",
      "Max Tomsick",
      "Leo Decter",
      "Jason Russo",
      "Sam Hinson",
      "Jack Waxman",
      "Ben Goldman",
    ],
    [
      "Vincent Calderon",
      "Roan Chadsey",
      "Chris Chan",
      "Davith Chan",
      "Nathaniel Chin",
      "Max Coleman",
      "Gabe Curran",
      "Peter Deckerman",
      "Sam Garncarz",
      "Jacob Groner",
      "Elliot Hare",
      "Reed Lonsdale",
      "Eric Ma",
      "Aidan Mackenzie",
      "James Mullmann",
      "Ben Myers",
      "Tomer Poole-Dayan",
      "Jason Russo",
      "Noah Schulman",
      "Neal Vasireddi",
      "Thomas Wu",
      "Thomas Zhao",
    ],
  ],
  [
    "2019-2020",
    y19_20,
    ["Rob Mertz", "Matt Burke", "Wally Kwong"],
    ["David Maniloff", "Max Kong", "Max Tomsick"],
    [
      "Vincent Calderon",
      "Roan Chadsey",
      "Chris Chan",
      "Nathaniel Chin",
      "Max Coleman",
      "Gabe Curran",
      "Peter Deckerman",
      "Leo Decter",
      "Rahul Dev",
      "Sam Garncarz",
      "Trevor Goldstein",
      "Sam Hinson",
      "Nick Hudson",
      "Alex Lindsay",
      "Reed Lonsdale",
      "Eric Ma",
      "Aidan Mackenzie",
      "James Mullmann",
      "Ben Myers",
      "Tomer Poole-Dayan",
      "Jason Russo",
      "Noah Schulman",
      "Neal Vasireddi",
      "Jack Waitz",
      "Jack Waxman",
      "Thomas Zhao",
    ],
  ],
  [
    "2018-2019",
    y18_19,
    ["Rob Mertz", "Matt Burke"],
    ["Spencer DeRoos", "Andrew Gavin", "Lucas Bulger"],
    [
      "Lucas Bulger",
      "Vincent Calderon",
      "Zac Chen",
      "Daniel Cohen",
      "Gabe Curran",
      "Leo Decter",
      "Plato Deliyannis",
      "Spencer DeRoos",
      "Andrew Gavin",
      "Trevor Goldstein",
      "Sam Hinson",
      "Binli Huang",
      "Nick Hudson",
      "Max Kong",
      "Kevin Liu",
      "Reed Lonsdale",
      "David Maniloff",
      "Simon Peck",
      "Jason Russo",
      "Noah Schulman",
      "Max Tomsick",
      "Neal Vasireddi",
      "Patrick Voorhees",
      "Chris Wan",
      "Jack Waxman",
      "Bryan Zheng",
    ],
  ],
  [
    "2017-2018",
    y17_18,
    ["Rob Mertz", "Veronica Chan"],
    ["Lito Avila", "Elie Lehmann", "Pat Voorhees"],
    [
      "Lito Avila",
      "Lucas Bulger",
      "Matt Burke",
      "Vincent Calderon",
      "Zac Chen",
      "Graham Cohen",
      "Gabe Curran",
      "Leo Decter",
      "Plato Deliyannis",
      "Spencer DeRoos",
      "Andrew Gavin",
      "Evan Greenberg",
      "Binli Huang",
      "Josh Klein",
      "Max Kong",
      "Elie Lehmann",
      "Aidan Mackenzie",
      "David Maniloff",
      "Jineet Patel",
      "Jason Russo",
      "Noah Schulman",
      "Randy Tang",
      "Max Tomsick",
      "Sam VanNoy",
      "Pat Voorhees",
      "Chris Wan",
      "Frank Wang",
      "Max Wrobel",
    ],
  ],
  [
    "2016-2017",
    y16_17,
    [],
    ["Robert Rickert", "Frank Wang", "Mike Hammer"],
    [
      "Lucas Bulger",
      "Vincent Calderon",
      "Zac Chen",
      "Graham Cohen",
      "Gabe Curran",
      "Plato Deliyannis",
      "Spencer DeRoos",
      "Wyatt Eberspacher",
      "Andrew Gavin",
      "Evan Greenberg",
      "Mike Hammer",
      "Levi Helms",
      "Binli Huang",
      "Max Kong",
      "Elie Lehmann",
      "Kevin Liu",
      "David Maniloff",
      "Tom Pera",
      "Donald Quinones",
      "Robert Rickert",
      "Jason Russo",
      "Noah Schulman",
      "Patrick Voorhees",
      "Christopher Wan",
      "Frank Wang",
      "Max Wrobel",
      "Bryan Zheng",
    ],
  ],
  [
    "2015-2016",
    y15_16,
    [],
    ["Joe Thompson", "Austin Hartley"],
    [
      "Lito Avila",
      "Zac Chen",
      "Spencer DeRoos",
      "Jordan Diamond",
      "Jake Dunoyer",
      "Wyatt Eberspacher",
      "Andrew Gavin",
      "Evan Greenberg",
      "Mike Hammer",
      "Levi Helms",
      "Jacob Herrera",
      "Austin Hartley",
      "Binli Huang",
      "Ethan Kannel",
      "Josh Klein",
      "Elie Lehmann",
      "Kevin Liu",
      "Chris Perrotti",
      "Robert Rickert",
      "Joe Thompson",
      "Carsten Thue-Bludworth",
      "Dan Vandam",
      "Chris Wan",
      "Frank Wang",
      "Bryan Zheng",
    ],
  ],
  [
    "2014-2015",
    y14_15,
    [],
    ["Daniel Wekstein", "Nate August", "Jordan Diamond"],
    [],
  ],
  [
    "2013-2014",
    y13_14,
    [],
    ["Jake Stevelman", "Walter Cai", "Franklin Li"],
    [],
  ],
  [
    "2012-2013",
    y12_13,
    [],
    ["Aiden Forsi", "Adam Salwen", "Jake Stevelman"],
    [],
  ],
  ["2011-2012", y11_12, [], ["Bo Li", "Nick Thompson", "Adam Salwen"], []],
  [
    "2010-2011",
    y10_11,
    [],
    ["Brian Grundy", "Alex Kadesch", "Neil Butler"],
    [],
  ],
  ["2009-2010", y09_10, [], ["Damien Lazar", "Art Shull", "Neil Butler"], []],
  [
    "2008-2009",
    y08_09,
    [],
    ["Bo Li", "Daniel Brager", "Damien Lazar", "Art Shull"],
    [],
  ],
  ["2007-2008", y07_08, [], ["Jono Berry", "Wilbur Kan", "Seth Reinhardt"], []],
];

export default rosters;
